import { MAX_TEXT_CHARS } from './config';
import { ApiClientError, patchSessionStatus, uploadQuestions } from './services/api-client';
import { readFromR2, TaskError } from './services/extract';
import { buildUserPrompt, GENERATE_SYSTEM_PROMPT, parseModelJson, validateQuestions } from './services/generate';
import { chatCompletion } from './services/llm';
import { ocrImages } from './services/ocr';
import { walkProviderChain } from './services/providers';
import { parseProviders } from './config';
import type { AppEnv, GenerateMessage } from './types';

type Bindings = AppEnv['Bindings'];

/**
 * 完整执行一次出题任务：
 * 验票 → 下载分诊 → OCR（仅图片）→ 组语料 → 多提供商生成 → 校验 → 入库
 */
export async function processGenerateMessage(message: GenerateMessage, env: Bindings): Promise<void> {
	const { ticket, materials } = message;
	const count = message.options?.count ?? 5;

	// 1. 验票 + 状态确认（受理端点已 PATCH 过 processing，这里是消费开始前的复查，
	//    防止 ticket 在排队期间过期或 session 已被其他路径终结）
	await patchSessionStatus(env.API_WORKER, ticket, 'processing');

	// 2. 从 R2 直读材料 + 格式分诊（不走公网预签名 URL）
	const material = await readFromR2(env.R2_BUCKET, materials);

	// 3. 图片走 OCR 转文字（生成永远只吃文本）
	let corpus = material.texts.join('\n\n');
	if (material.images.length > 0) {
		const providers = parseProviders(env.AI_PROVIDERS);
		const { result: ocrText } = await walkProviderChain(
			env,
			providers,
			(provider, apiKey) =>
				ocrImages({
					baseUrl: provider.baseUrl,
					apiKey,
					model: provider.ocrModel as string,
					images: material.images,
				}),
			(p) => !!p.ocrModel,
		);
		corpus = [corpus, ocrText].filter(Boolean).join('\n\n');
	}

	if (!corpus.trim()) {
		throw new TaskError('未能从文档中获得任何文本内容（可能是无法识别的扫描件）');
	}
	if (corpus.length > MAX_TEXT_CHARS) {
		throw new TaskError(`材料文本超过上限（${MAX_TEXT_CHARS} 字符），请拆分文档后重试`);
	}

	// 4. 生成题目（按提供商优先级故障切换）
	const providers = parseProviders(env.AI_PROVIDERS);
	const { result: rawOutput, provider } = await walkProviderChain(env, providers, (p, apiKey) =>
		chatCompletion({
			baseUrl: p.baseUrl,
			apiKey,
			model: p.generateModel,
			messages: [
				{ role: 'system', content: GENERATE_SYSTEM_PROMPT },
				{ role: 'user', content: buildUserPrompt(corpus, count) },
			],
			jsonOutput: true,
		}),
	);
	console.log(`Questions generated by provider "${provider.name}" (model=${provider.generateModel})`);

	// 5. 解析 + 逐题校验（不合格的直接丢弃）
	const questions = validateQuestions(parseModelJson(rawOutput));
	if (questions.length === 0) {
		throw new TaskError('模型输出中没有合格题目（JSON 解析失败或全部未通过校验）');
	}

	// 6. 入库（成功后 API 项目自动把 session 置为 completed，ticket 随即作废）
	await uploadQuestions(env.API_WORKER, ticket, questions);
	console.log(`Uploaded ${questions.length} questions for session ${ticket}`);
}

/**
 * 队列消息处理外壳：区分"基础设施错误"（抛出，交给队列重试）
 * 和"业务失败 / 终态"（尽力标记 failed 后确认消费，不重试）。
 */
export async function handleGenerateMessage(message: GenerateMessage, env: Bindings): Promise<void> {
	try {
		await processGenerateMessage(message, env);
	} catch (err) {
		// API 项目返回 4xx：ticket 已处于终态（completed/failed/过期），无需再处理
		if (err instanceof ApiClientError && err.status < 500) {
			console.warn(`Session ${message.ticket} already in terminal state or ticket invalid, acknowledging message:`, err.message);
			return;
		}

		// API 项目 5xx / 网络层错误：交给队列重试
		if (err instanceof ApiClientError && err.status >= 500) {
			console.error(`API project unavailable, will retry via queue:`, err);
			throw err;
		}

		// 其他（TaskError / 提供商链全部失败 / 下载失败等）：业务失败，标记 failed 后终结
		console.error(`Generation task failed for session ${message.ticket}:`, err);
		try {
			await patchSessionStatus(env.API_WORKER, message.ticket, 'failed');
		} catch (markErr) {
			console.error('Failed to mark session as failed:', markErr);
		}
	}
}
