import { GENERATION_BATCH_SIZE, GENERATION_MAX_TOKENS, MAX_TEXT_CHARS, PLAN_MAX_TOKENS } from './config';
import { parseProviders } from './config';
import { ApiClientError, patchSessionStatus, renewTicket, uploadQuestions } from './services/api-client';
import { readFromR2, TaskError } from './services/extract';
import {
	buildBatchUserPrompt,
	buildPlanUserPrompt,
	extractStems,
	GENERATE_SYSTEM_PROMPT,
	GenerationPlan,
	parseModelJson,
	PLAN_SYSTEM_PROMPT,
	validateQuestions,
} from './services/generate';
import { chatCompletion } from './services/llm';
import { ocrImages } from './services/ocr';
import { walkProviderChain } from './services/providers';
import type { AppEnv, GenerateMessage, GeneratedQuestion } from './types';

type Bindings = AppEnv['Bindings'];

/**
 * 完整执行一次出题任务：
 * 验票 → 下载分诊 → OCR（仅图片）→ 组语料 → 多提供商生成 → 校验 → 入库
 */
export async function processGenerateMessage(message: GenerateMessage, env: Bindings): Promise<void> {
	const { ticket, materials } = message;

	// 1. 验票 + 状态确认（受理端点已 PATCH 过 processing，这里是消费开始前的复查，
	//    防止 ticket 在排队期间过期或 session 已被其他路径终结）
	await patchSessionStatus(env.API_WORKER, ticket, 'processing');

	// 2. 从 R2 直读材料 + 格式分诊（不走公网预签名 URL）
	const material = await readFromR2(env.R2_BUCKET, materials);

	// 3. 图片走 OCR 转文字（生成永远只吃文本）
	let corpus = material.texts.join('\n\n');
	if (material.images.length > 0) {
		const providers = parseProviders(env.AI_PROVIDERS);
		const { result: ocrText } = await walkProviderChain(
			env,
			providers,
			(provider, apiKey) =>
				ocrImages({
					baseUrl: provider.baseUrl,
					apiKey,
					model: provider.ocrModel as string,
					images: material.images,
				}),
			(p) => !!p.ocrModel,
		);
		corpus = [corpus, ocrText].filter(Boolean).join('\n\n');
	}

	if (!corpus.trim()) {
		throw new TaskError('未能从文档中获得任何文本内容（可能是无法识别的扫描件）');
	}
	if (corpus.length > MAX_TEXT_CHARS) {
		throw new TaskError(`材料文本超过上限（${MAX_TEXT_CHARS} 字符），请拆分文档后重试`);
	}

	// 4. 两阶段生成：规划 → 分批生成
	const providers = parseProviders(env.AI_PROVIDERS);

	// 4a. Phase 1 — 规划：模型分析材料，决定题目总数和题型分布
	const { result: planRaw, provider: planProvider } = await walkProviderChain(env, providers, (p, apiKey) =>
		chatCompletion({
			baseUrl: p.baseUrl,
			apiKey,
			model: p.generateModel,
			messages: [
				{ role: 'system', content: PLAN_SYSTEM_PROMPT },
				{ role: 'user', content: buildPlanUserPrompt(corpus) },
			],
			jsonOutput: true,
			maxTokens: PLAN_MAX_TOKENS,
		}),
	);
	console.log(`Plan generated by provider "${planProvider.name}" (model=${planProvider.generateModel})`);

	const planParsed = parseModelJson(planRaw) as Record<string, unknown> | null;
	const plan: GenerationPlan = {
		totalCount: typeof planParsed?.totalCount === 'number' ? planParsed.totalCount : 0,
		types: Array.isArray(planParsed?.types) ? (planParsed.types as string[]).filter((t) => typeof t === 'string') : [],
	};
	if (plan.totalCount < 1 || plan.types.length === 0) {
		throw new TaskError('规划阶段输出异常（totalCount 或 types 无效）');
	}
	console.log(`Plan: ${plan.totalCount} questions, types=[${plan.types.join(', ')}]`);

	// 续期 ticket（规划阶段可能已耗时较长）
	// 4xx = session 已被取消/失效 → 中止 pipeline；5xx = 暂态故障 → 记日志继续
	try {
		await renewTicket(env.API_WORKER, ticket);
		console.log('Ticket renewed after planning phase');
	} catch (err) {
		if (err instanceof ApiClientError && err.status < 500) {
			console.warn('Ticket renewal rejected (4xx) after planning, session likely cancelled:', err.message);
			throw err;
		}
		console.error('Failed to renew ticket after planning (non-fatal):', err);
	}

	// 4b. Phase 2 — 分批生成：每批最多 GENERATION_BATCH_SIZE 道题
	const totalBatches = Math.ceil(plan.totalCount / GENERATION_BATCH_SIZE);
	const allQuestions: GeneratedQuestion[] = [];
	let allStems: string[] = [];

	for (let batchIndex = 1; batchIndex <= totalBatches; batchIndex++) {
		const remaining = plan.totalCount - allQuestions.length;
		const batchSize = Math.min(GENERATION_BATCH_SIZE, remaining);

		const { result: batchRaw, provider: batchProvider } = await walkProviderChain(env, providers, (p, apiKey) =>
			chatCompletion({
				baseUrl: p.baseUrl,
				apiKey,
				model: p.generateModel,
				messages: [
					{ role: 'system', content: GENERATE_SYSTEM_PROMPT },
					{
						role: 'user',
						content: buildBatchUserPrompt(corpus, plan, batchIndex, batchSize, totalBatches, allStems),
					},
				],
				jsonOutput: true,
				maxTokens: GENERATION_MAX_TOKENS,
			}),
		);
		console.log(`Batch ${batchIndex}/${totalBatches} generated by "${batchProvider.name}" (raw length=${batchRaw.length})`);

		const batchQuestions = validateQuestions(parseModelJson(batchRaw));
		allQuestions.push(...batchQuestions);
		allStems = extractStems(allQuestions);

		console.log(`Batch ${batchIndex}: ${batchQuestions.length} valid questions (total so far: ${allQuestions.length})`);

		// 每批完成后续期 ticket，防止长时间生成导致过期
		// 4xx = session 已被取消/失效 → 中止 pipeline；5xx = 暂态故障 → 记日志继续
		try {
			await renewTicket(env.API_WORKER, ticket);
		} catch (err) {
			if (err instanceof ApiClientError && err.status < 500) {
				console.warn(`Ticket renewal rejected (4xx) after batch ${batchIndex}, session likely cancelled:`, err.message);
				throw err;
			}
			console.error(`Failed to renew ticket after batch ${batchIndex} (non-fatal):`, err);
		}
	}

	if (allQuestions.length === 0) {
		throw new TaskError('所有批次中没有合格题目（JSON 解析失败或全部未通过校验）');
	}

	// 5. 入库（成功后 API 项目自动把 session 置为 completed，ticket 随即作废）
	await uploadQuestions(env.API_WORKER, ticket, allQuestions);
	console.log(`Uploaded ${allQuestions.length} questions for session ${ticket}`);
}

/**
 * 队列消息处理外壳：区分"基础设施错误"（抛出，交给队列重试）
 * 和"业务失败 / 终态"（尽力标记 failed 后确认消费，不重试）。
 */
export async function handleGenerateMessage(message: GenerateMessage, env: Bindings): Promise<void> {
	try {
		await processGenerateMessage(message, env);
	} catch (err) {
		// API 项目返回 4xx：ticket 已处于终态（completed/failed/过期），无需再处理
		if (err instanceof ApiClientError && err.status < 500) {
			console.warn(`Session ${message.ticket} already in terminal state or ticket invalid, acknowledging message:`, err.message);
			return;
		}

		// API 项目 5xx / 网络层错误：交给队列重试
		if (err instanceof ApiClientError && err.status >= 500) {
			console.error(`API project unavailable, will retry via queue:`, err);
			throw err;
		}

		// 其他（TaskError / 提供商链全部失败 / 下载失败等）：业务失败，标记 failed 后终结
		console.error(`Generation task failed for session ${message.ticket}:`, err);
		try {
			await patchSessionStatus(env.API_WORKER, message.ticket, 'failed');
		} catch (markErr) {
			console.error('Failed to mark session as failed:', markErr);
		}
	}
}
